create table inventoryItems (id bigint generated by default as identity (start with 1), quantityOnHand integer not null, product_id bigint, primary key (id));
create table lineItems (id bigint generated by default as identity (start with 1), quantity integer not null, unitPrice double not null, order_id bigint, product_id bigint, primary key (id));
create table orders (id bigint generated by default as identity (start with 1), placed bit not null, primary key (id));
create table products (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255), price double not null, primary key (id));
alter table inventoryItems add constraint FKFCD057C4A752F29D foreign key (product_id) references products;
alter table lineItems add constraint FK93BC202CF6FFD6FD foreign key (order_id) references orders;
alter table lineItems add constraint FK93BC202CA752F29D foreign key (product_id) references products;
